Document anonymous access and limitations
hassio-addons/addon-grafana pull request #101
Opened 2021-02-04 15:20 UTC by deviantintegral

# Proposed Changes

This follows up from my question at #100 with notes on how to set up local access and limitations for cloud access.

2021-02-12 17:28 UTC, frenck requested changes

2021-02-12 17:28 UTC, frenck commented on grafana/DOCS.md
> +addon config, along with setting the following environment variables:
```suggestion
add-on config, along with setting the following environment variables:
```

2021-02-12 17:28 UTC, frenck commented on grafana/DOCS.md
> +rendered image inside of a dashboard. For more details see
```suggestion
rendered image inside of a dashboard. For more details see:
```

2021-02-12 17:28 UTC, frenck commented on grafana/DOCS.md
> +[Anonymous login not working, Grafan add-on 3.0.0 #55](https://github.com/hassio-addons/addon-grafana/issues/55).
```suggestion

- ["“401: Unauthorized” iframe CARD of Grafana not working"](https://community.home-assistant.io/t/401-unauthorized-iframe-card-of-grafana-not-working/148017)
and
- [Anonymous login not working, Grafana add-on 3.0.0 #55](https://github.com/hassio-addons/addon-grafana/issues/55).
```

2021-02-12 17:29 UTC, frenck commented
Additionally requested a review from @sinclairpaul, he knows the most about this.

2021-02-12 17:41 UTC, sinclairpaul commented
Grafana supports publishing snapshots I believe, which automatically sets up anonymous access, wouldn't that be the preferred approach rather than essentially opening the instance to anyone?

I haven't looked at it in detail, so may need some config adjustment to function, but the details can be found at:

https://grafana.com/docs/grafana/latest/sharing/share-panel/

I will also add, I'm really not a fan of iFraming anything, and as browser security becomes stricter it becomes more challenging.  We should probably at least add a note around samesite config .

2021-02-17 21:32 UTC, deviantintegral commented
Thanks for the review.

> Grafana supports publishing snapshots I believe, which automatically sets up anonymous access, wouldn't that be the preferred approach rather than essentially opening the instance to anyone?

The issue with that feature is that it limits the data to what the snapshot was created with. It doesn't expose data logged after the snapshot was created. The other option is embeds, but those are tied to your authentication state.

The share panel offers embeds which are meant to be accessed through an iframe, but they're tied to the authentication state.

2021-02-17 21:33 UTC, deviantintegral commented
Re iframes, how about I link that to https://grafana.com/docs/grafana/latest/sharing/share-panel/#embed-panel so it's clear that's what I'm referring to? I assume for same-site that Grafana explicitly doesn't set that given their examples use iframes.

2021-02-18 02:40 UTC, sinclairpaul commented
Thanks, if the snapshot links aren't updated it makes sense.

My only last comment is linking to forum posts that could vanish maybe??, other than that I am good.

2021-02-18 07:55 UTC, frenck commented
Yeah, I agree with @sinclairpaul there.

2021-02-23 13:23 UTC, sinclairpaul commented
Just one last thought, Grafana does offer API auth, does this work for dashboards?

https://grafana.com/docs/grafana/latest/http_api/auth/

Sorry it took me a while to find it (I thought it was there somewhere), it looks like it can be passed as Basic Auth, and may be preferable than opening the whole instance up.

2021-02-26 12:04 UTC, deviantintegral commented
If the point is to give access to viewers to the Grafana dashboards, I don't think HTTP basic will help. For example, Safari no longer passes through credentials in a URL as HTTP basic headers, requiring the user to put them in again.

2021-03-29 12:05 UTC, deviantintegral commented
I think we're pretty close here! Let me know if there's anything else to do.

2021-04-10 10:32 UTC, frenck commented on grafana/DOCS.md
> +add-on config, along with setting the following environment variables:
```suggestion
Anonymous access on a local network is possible by exposing the port in the
add-on configuration, along with setting the following environment variables:
```

2021-04-10 10:36 UTC, merged