Update config.json
hassio-addons/addon-grafana pull request #93
Opened 2021-01-24 09:48 UTC by norgan

Grafana API requires port 3000 to work. When deployed via hassio, this container does not have 3000 NAT'ed from the host to it. This means we cannot import sources etc, we get a 502 bad gateway. Even when publishing a reverse proxy rule this does not work, however, the basic all will work from outside directly to the container IP. What needs to happen is port 3000 listening on the host so that calls can then be sent into the container to the grafana API, or they can be proxied properly then.

# Proposed Changes

> (Describe the changes and rationale behind them)

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

2021-01-24 15:53 UTC, frenck commented
My first impression is, this change is incorrect (and definitely breaking). But I'm missing something I guess. Will take a look!

2021-01-24 22:47 UTC, norgan commented
Thanks, I'm trying to get it working in a container. Right now it cannot take api calls and gives 502 bad gateway.
So it's either this port or an nginx proxy config issue.
________________________________
From: Franck Nijhof <notifications@github.com>
Sent: Monday, January 25, 2021 2:53:43 AM
To: hassio-addons/addon-grafana <addon-grafana@noreply.github.com>
Cc: Nathan Organ <nath@norgan.net>; Author <author@noreply.github.com>
Subject: Re: [hassio-addons/addon-grafana] Update config.json (#93)


My first impression is, this change is incorrect (and definitely breaking). But I'm missing something I guess. Will take a look!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/hassio-addons/addon-grafana/pull/93#issuecomment-766371776>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAIJYKNIZSJEEPI42FMT74DS3Q7APANCNFSM4WQMZQLA>.

2021-01-24 23:10 UTC, sinclairpaul commented
Please see #60

I actually think it is ingress related, as if you copy and paste the config in it works fine.

2021-01-24 23:12 UTC, norgan commented
It's absolutely and ingress issue. Port 3000 is not available outside of the container. However it's deployed using the hass add-on, doesn't work when deployed.
What config are you saying needs to be pasted and where?
________________________________
From: Paul Sinclair <notifications@github.com>
Sent: Monday, January 25, 2021 10:10:14 AM
To: hassio-addons/addon-grafana <addon-grafana@noreply.github.com>
Cc: Nathan Organ <nath@norgan.net>; Author <author@noreply.github.com>
Subject: Re: [hassio-addons/addon-grafana] Map port 3000 instead of 80 for Grafana's external ports (#93)


Please see #60<https://github.com/hassio-addons/addon-grafana/issues/60>

I actually think it is ingress related, as if you copy and paste the config in it works fine.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/hassio-addons/addon-grafana/pull/93#issuecomment-766456674>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAIJYKNGHSKNC2SKOYUKVGTS3SSFNANCNFSM4WQMZQLA>.

2021-01-24 23:17 UTC, sinclairpaul commented
If you download the json, then choose `Import via panel json`, it will work fine.

2021-01-24 23:17 UTC, frenck requested changes
This is actually incorrect, it no longer honors the SSL settings.
Please ensure the SSL settings work as well.

2021-01-24 23:19 UTC, norgan commented
I'm doing an azure monitor integration so I'm trying to import it following the guide. It's all set up and validates but won't import.
What you are doing is a file from the browser to the service. I'm trying to pull from an external service.
________________________________
From: Paul Sinclair <notifications@github.com>
Sent: Monday, January 25, 2021 10:17:39 AM
To: hassio-addons/addon-grafana <addon-grafana@noreply.github.com>
Cc: Nathan Organ <nath@norgan.net>; Author <author@noreply.github.com>
Subject: Re: [hassio-addons/addon-grafana] Map port 3000 instead of 80 for Grafana's external ports (#93)


If you download the json, then choose Import via panel json, it will work fine.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/hassio-addons/addon-grafana/pull/93#issuecomment-766457789>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAIJYKMLIM436PMU4LWQDRTS3STBHANCNFSM4WQMZQLA>.

2021-01-30 13:32 UTC, frenck commented
This PR is wrong and the user has been banned from our org. Closing this.

2021-01-30 13:32 UTC, closed without merging